require 'user.options'
require 'user.keymap'
require 'user.plugins'
require 'user.gitsigns'
require 'user.cmp'
require 'user.lsp.init'
require 'user.telescope'
require 'user.autopairs'
-- gruvbox should be added by plugins ^^
-- vim.cmd 'colorscheme gruvbox'
